typography_spectrum: 0.48761391011066735
color:
  brandColors:
    - '#ffffff'
    - '#80a47d'
    - '#c77652'
    - '#d5a688'
    - '#e3ebe3'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.4582727113738656
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4896
analytics:
  google: null
  facebook: null
  twitter: null
name: edfrost.org
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Edward Frost '
description: 'One. Life. '
purpose: []
