name: eddyfrost
favicon: null
layout_spectrum: 0.4896
typography_spectrum: 0.48761391011066735
title: 'Edward Frost '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#80a47d'
    - '#c77652'
    - '#d5a688'
    - '#e3ebe3'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.4582727113738656
purpose: []
